# Generated by Django 5.1.2 on 2024-10-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=60)),
                ('year', models.PositiveIntegerField()),
                ('semester', models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2')], max_length=10)),
                ('student_photo', models.ImageField(upload_to='student_photos/')),
                ('project_photo', models.FileField(upload_to='project_photos/')),
                ('short_paper', models.FileField(upload_to='papers/')),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
