# Generated by Django 5.1.2 on 2024-10-30 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerge', '0003_alter_project_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='short_paper',
            field=models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx'])]),
        ),
    ]
