# Generated by Django 5.1.2 on 2024-10-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerge', '0004_alter_project_short_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.FileField(upload_to='project_photos/'),
        ),
    ]
