# Generated by Django 5.1.2 on 2024-10-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emerge', '0005_alter_project_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(upload_to='project_photos/'),
        ),
    ]
